annotations:
  category: Infrastructure
apiVersion: v2
# App version follows crossplane AWS provider version.
appVersion: "0.37.0-3"
description: A Helm chart for IAC resources needed to access EKS cluster
name: aws-eks-rbac
version: "0.37.0-4"
home: https://helm-repo-public.luminarinfra.com/
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/infra/aws-eks-rbac
maintainers:
  - name: Luminar SRE Team
    email: sre@luminartech.com
dependencies:
  - name: crossplane-aws-iam
    version: "0.37.0-1"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: crossplane-aws-iam.enabled
  - name: crossplane-kubernetes
    version: "0.4.0-2"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: crossplane-kubernetes.enabled
  - name: crossplane
    version: "1.13.2-15"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: crossplane.enabled
