annotations:
  category: Infrastructure
apiVersion: v2
# App version follows crossplane AWS provider version.
appVersion: "0.41.0"
description: A Helm chart for IAC resources needed to access EKS cluster
name: aws-eks-rbac
version: "0.41.0"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/infra/aws-eks-rbac
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: crossplane-kubernetes
    version: "0.11.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-kubernetes.enabled
