annotations:
  category: Infrastructure
apiVersion: v2
# App version follows crossplane AWS provider version.
appVersion: "0.41.0"
description: A Helm chart for IAC resources needed by EKS
name: aws-eks
version: "0.41.0-9"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/infra/aws-eks
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: crossplane-aws-ec2
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-ec2.enabled
  - name: external-secrets
    version: "0.9.13-2"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: external-secrets.enabled
  - name: crossplane-aws-kms
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-kms.enabled
  - name: crossplane-aws-eks
    version: "0.41.0-1"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-eks.enabled
