---
## AWS Database resources configurations

DBSubnetGroup:
  enabled: true
  items:
    _:
      deletionPolicy: Delete
      forProvider:
        region: us-east-1
        description: "sample group"
        subnetIdRefs:
          - name: sample-subnet1
          - name: sample-subnet2

RDSInstance:
  enabled: true
  items:
    _:
      deletionPolicy: Delete
      forProvider:
        region: us-east-1
        allocatedStorage: 20
        autoMinorVersionUpgrade: true
        backupRetentionPeriod: 0
        caCertificateIdentifier: rds-ca-2019
        copyTagsToSnapshot: false
        dbInstanceClass: db.t3.small
        deletionProtection: false
        enableIAMDatabaseAuthentication: false
        enablePerformanceInsights: false
        engine: mysql
        engineVersion: 8.0.28
        finalDBSnapshotIdentifier: muvaf-test
        licenseModel: general-public-license
        masterUsername: admin
        multiAZ: true
        port: 3306
        publiclyAccessible: false
        storageEncrypted: false
        storageType: gp2
