ClusterRole:
  enabled: true
  items:
    _:
      enabled: true
      rules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]

RoleBinding:
  enabled: true
  items:
    gitlab-statefulset:
      enabled: true
      namespace: gitlab-stateful-runner
      roleRef:
        kind: ClusterRole
        name: '{{ include "common-gitops.names.release" . }}'
      subjects:
        - kind: Group
          name: 'team-bre'
    gitlab-deployment:
      enabled: true
      namespace: gitlab-runner
      roleRef:
        kind: ClusterRole
        name: '{{ include "common-gitops.names.release" . }}'
      subjects:
        - kind: Group
          name: 'team-bre'
