{{- $kind := "Object" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if eq (include "common-gitops.utils.itemEnabled" (dict "root" $root "name" $name "kind" $kind)) "true" }}
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
spec:
    {{- with .connectionDetails }}
  connectionDetails:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
    {{- end }}
    {{- include "common-gitops.crossplane.deletionPolicy" (dict "root" $root "name" $name "kind" $kind) | nindent 2 }}
    {{- include "common-gitops.crossplane.forProvider" (dict "root" $root "values" (.forProvider) "valuesOverride" (dict
      )) | nindent 2 }}
    {{- with .managementPolicy }}
  managementPolicy: "{{ . }}"
    {{- end }}
    {{- with .readiness }}
  readiness:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
    {{- end }}
    {{- with .references }}
  references:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
    {{- end }}
    {{- include "common-gitops.crossplane.publishConnectionDetailsTo" (dict "root" $root "name" $name "kind" $kind "nameOverride" .name) | nindent 2 }}
    {{- include "common-gitops.crossplane.writeConnectionSecretToRef" (dict "root" $root "name" $name "kind" $kind "nameOverride" .name) | nindent 2 }}
    {{- include "common-gitops.crossplane.providerConfigRef" (dict "root" $root "name" $name "kind" $kind) | nindent 2 }}
  {{- end }}
{{- end }}
