{{- $kind := "ProviderConfig" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if hasKey $item "enabled" | ternary ($item.enabled) (ne $kindObj.enabled false) }}
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
spec:
    {{- with .credentials }}
  credentials:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
    {{- end }}
    {{- with .identity }}
  identity:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
    {{- end }}
  {{- end -}}
{{- end }}
