annotations:
  category: Infrastructure
apiVersion: v2
appVersion: "1.5.0"
description: A Helm chart for karpenter + related resources
name: karpenter
version: "1.5.0"
home: https://helm-repo-public.luminarinfra.com/
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/karpenter
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: common-gitops
    version: "1.1.11"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: crossplane-aws-sqs
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-sqs.enabled
  - name: crossplane-aws-cloudwatch
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-cloudwatch.enabled
  - name: karpenter
    version: "1.5.0"
    repository: "oci://public.ecr.aws/karpenter"
    condition: karpenter.enabled
    # Karpenter helm chart only creates CRDs during the first install.
    # There's a separate helm chart for managing them afterwards.
  - name: karpenter-crd
    version: "1.5.0"
    repository: "oci://public.ecr.aws/karpenter"
    condition: karpenter-crd.enabled
