{
 "title": "Crossplane",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Crossplane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reconciles by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by (controller) (rate(controller_runtime_reconcile_total{job=\"infra-crossplane/crossplane-metrics\"}[$__rate_interval])))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "API Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(rest_client_requests_total{job=\"infra-crossplane/crossplane-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (workqueue_depth{job=\"infra-crossplane/crossplane-metrics\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Duration",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_queue_duration_seconds_bucket{job=\"infra-crossplane/crossplane-metrics\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Server Requests by Resource (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (resource) (rate(apiserver_request_total[$__rate_interval])))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Server Errors by Resource and Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code, resource) (rate(apiserver_request_total{code=~\"[45][0-9][0-9]\"}[$__rate_interval]))",
     "legendFormat": "{{code}} ({{resource}})"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API Server Started",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"apiserver\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(process_cpu_seconds_total{job=\"apiserver\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server CRDs Added",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count(count by (crd) (apiextensions_openapi_v2_regeneration_count{job=\"apiserver\", reason=\"add\"}))",
     "legendFormat": "CRDs"
    }
   ]
  },
  {
   "title": "API Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (process_resident_memory_bytes{job=\"apiserver\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 29 },
   "targets": [
    {
     "expr": "sum by (instance) (go_goroutines{job=\"apiserver\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}