{
 "title": "External Secrets Operator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{service=~\".*external-secrets.*\"},  controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SecretStore error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"secretstore\", result=\"error\"}[15m])))\n/\n(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"secretstore\"}[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ClusterSecretStore error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"clustersecretstore\", result=\"error\"}[15m])))\n/\n(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"clustersecretstore\"}[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ExternalSecret error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"externalsecret\", result=\"error\"}[15m])))\n/\n(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"externalsecret\"}[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ClusterExternalSecret error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"clusterexternalsecret\", result=\"error\"}[15m])))\n/\n(sum(irate(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"clusterexternalsecret\"}[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PushSecret error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"pushsecret\", result=\"error\"}[15m])))\n/\n(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"pushsecret\"}[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\", status=\"error\"}[15m]))\n/\nsum(increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue depth",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  workqueue_depth{service=~\"external-secrets.*\"}\n) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_webhook_requests_total{service=~\"external-secrets.*\",code=\"500\"}[15m]))\n/\nsum(increase(controller_runtime_webhook_requests_total{service=~\"external-secrets.*\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook latency [5m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(rate(controller_runtime_webhook_latency_seconds_bucket{service=~\"external-secrets.*\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile latency [p99]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(rate(controller_runtime_reconcile_time_seconds_bucket{service=~\"external-secrets.*\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconcile error rate [p99]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{service=~\"external-secrets.*\",controller=~\"$controller\",result=\"error\"}[1m]))\n/\nsum(increase(controller_runtime_reconcile_total{service=~\"external-secrets.*\",controller=~\"$controller\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider errors [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\", status=\"error\"}[15m])",
     "legendFormat": "{{provider}}/{{call}}"
    }
   ]
  },
  {
   "title": "Not Ready ExternalSecrets  [15m]",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(externalsecret_status_condition{condition=\"Ready\",status=\"False\"}) by (namespace, name) == 1",
     "legendFormat": "{{provider}}/{{call}}"
    }
   ]
  },
  {
   "title": "ExternalSecret sync call errors [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(externalsecret_sync_calls_error[15m])) by (name, namespace)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Admission Control Webhook",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "requests by path per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_webhook_requests_total{service=~\".*external-secrets.*\"}[1m])) by (webhook)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "requests in flight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "sum(controller_runtime_webhook_requests_in_flight{service=~\".*external-secrets.*\"}) by (webhook)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "requests by code per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_webhook_requests_total{service=~\".*external-secrets.*\"}[1m])) by (code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "webhook latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_webhook_latency_seconds_bucket{service=~\".*external-secrets.*\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controllers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "active workers by controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(controller_runtime_active_workers{service=~\".*external-secrets.*\",controller=~\"$controller\"}) by (controller)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "workqueue depth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 17 },
     "targets": [
      {
       "expr": "sum(workqueue_depth{service=~\".*external-secrets.*\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API calls by provider",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
     "targets": [
      {
       "expr": "sum(increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\"}[1m])) by(provider, call, status)",
       "legendFormat": "{{provider}}/{{call}}={{status}}"
      }
     ]
    },
    {
     "title": "max concurrent: $controller",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 0, "y": 25 },
     "repeat": "controller",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(controller_runtime_max_concurrent_reconciles{service=~\".*external-secrets.*\",controller=\"$controller\"}) by (controller)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "reconcile rate per minute: $controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 31 },
     "repeat": "controller",
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"$controller\"}[1m])) by (result)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "reconcile time latency: $controller",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 39 },
     "repeat": "controller",
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_time_seconds_bucket{service=~\".*external-secrets.*\",controller=~\"$controller\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}