{
 "title": "Loki & Promtail",
 "description": "Loki and Promtail metrics.",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Loki's stored chunk entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(loki_ingester_chunk_entries_count[5m])"
    }
   ]
  },
  {
   "title": "Average batch appends sent to ingesters (Loki)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (loki_distributor_ingester_appends_total[1m])"
    }
   ]
  },
  {
   "title": "Number of bytes total by promtail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (promtail_file_bytes_total{instance=~\".*\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Number of bytes encoded and ready to send by Promtail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (promtail_encoded_bytes_total{pod=~'.*'}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}