{
 "title": "Trivy Vulnerabilities",
 "description": "Dashboard for Trivy Operator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(max(trivy_image_vulnerabilities{severity=\"Critical\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) )   ",
     "group": [
      {
       "params": [
        "$__interval",
        "none"
       ],
       "type": "time"
      }
     ],
     "round": "0s",
     "select": [
      [
       { "params": [ "id" ], "type": "column" },
       { "params": [ "count" ], "type": "aggregate" },
       { "params": [ "id" ], "type": "alias" }
      ]
     ],
     "table": "vulnerability",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      },
      {
       "datatype": "int4",
       "name": "",
       "params": [
        "host_id",
        "!=",
        "None"
       ],
       "type": "expression"
      }
     ]
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(max(trivy_image_vulnerabilities{severity=\"High\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ))",
     "group": [
      {
       "params": [
        "$__interval",
        "none"
       ],
       "type": "time"
      }
     ],
     "round": "0s",
     "select": [
      [
       { "params": [ "id" ], "type": "column" },
       { "params": [ "count" ], "type": "aggregate" },
       { "params": [ "id" ], "type": "alias" }
      ]
     ],
     "table": "vulnerability",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      },
      {
       "datatype": "int4",
       "name": "",
       "params": [
        "host_id",
        "!=",
        "None"
       ],
       "type": "expression"
      }
     ]
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(max(trivy_image_vulnerabilities{severity=\"Medium\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ))",
     "group": [
      {
       "params": [
        "$__interval",
        "none"
       ],
       "type": "time"
      }
     ],
     "round": "0s",
     "select": [
      [
       { "params": [ "id" ], "type": "column" },
       { "params": [ "count" ], "type": "aggregate" },
       { "params": [ "id" ], "type": "alias" }
      ]
     ],
     "table": "vulnerability",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      },
      {
       "datatype": "int4",
       "name": "",
       "params": [
        "host_id",
        "!=",
        "None"
       ],
       "type": "expression"
      }
     ]
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(max(trivy_image_vulnerabilities{severity=\"Low\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ))",
     "group": [
      {
       "params": [
        "$__interval",
        "none"
       ],
       "type": "time"
      }
     ],
     "round": "0s",
     "select": [
      [
       { "params": [ "id" ], "type": "column" },
       { "params": [ "count" ], "type": "aggregate" },
       { "params": [ "id" ], "type": "alias" }
      ]
     ],
     "table": "vulnerability",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      },
      {
       "datatype": "int4",
       "name": "",
       "params": [
        "host_id",
        "!=",
        "None"
       ],
       "type": "expression"
      }
     ]
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(max(trivy_image_vulnerabilities{severity=\"Unknown\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ))",
     "group": [
      {
       "params": [
        "$__interval",
        "none"
       ],
       "type": "time"
      }
     ],
     "round": "0s",
     "select": [
      [
       { "params": [ "id" ], "type": "column" },
       { "params": [ "count" ], "type": "aggregate" },
       { "params": [ "id" ], "type": "alias" }
      ]
     ],
     "table": "vulnerability",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      },
      {
       "datatype": "int4",
       "name": "",
       "params": [
        "host_id",
        "!=",
        "None"
       ],
       "type": "expression"
      }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(max(trivy_image_vulnerabilities{severity=\"Critical\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) + max(trivy_image_vulnerabilities{severity=\"High\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) + max(trivy_image_vulnerabilities{severity=\"Medium\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) + max(trivy_image_vulnerabilities{severity=\"Low\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) + max(trivy_image_vulnerabilities{severity=\"Unknown\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ))",
     "group": [
      {
       "params": [
        "$__interval",
        "none"
       ],
       "type": "time"
      }
     ],
     "round": "0s",
     "select": [
      [
       { "params": [ "id" ], "type": "column" },
       { "params": [ "count" ], "type": "aggregate" },
       { "params": [ "id" ], "type": "alias" }
      ]
     ],
     "table": "vulnerability",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      },
      {
       "datatype": "int4",
       "name": "",
       "params": [
        "host_id",
        "!=",
        "None"
       ],
       "type": "expression"
      }
     ]
    }
   ]
  },
  {
   "title": "Image Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 41, "w": 17, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(trivy_image_vulnerabilities{severity=\"Critical\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) ",
     "legendFormat": "Critical"
    },
    {
     "expr": "max(trivy_image_vulnerabilities{severity=\"High\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) ",
     "legendFormat": "High"
    },
    {
     "expr": "max(trivy_image_vulnerabilities{severity=\"Critical\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) + max(trivy_image_vulnerabilities{severity=\"High\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) + max(trivy_image_vulnerabilities{severity=\"Medium\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) + max(trivy_image_vulnerabilities{severity=\"Low\"})  by (image_registry, image_repository, image_tag, image_digest, namespace ) + max(trivy_image_vulnerabilities{severity=\"Unknown\"})  by (image_registry, image_repository, image_tag,image_digest, namespace ) ",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}