annotations:
  category: Application
apiVersion: v2
appVersion: "45.7.1"
description: A Helm chart for monitoring
name: monitoring
version: "45.7.1-6"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/monitoring
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: kube-prometheus-stack
    version: "56.18.0"
    repository: https://prometheus-community.github.io/helm-charts
