annotations:
  category: Application
apiVersion: v2
appVersion: "0.71.2"
description: A Helm chart for monitoring
name: monitoring
version: "56.19.0-3"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/monitoring
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: kube-prometheus-stack
    version: "56.19.0"
    repository: https://prometheus-community.github.io/helm-charts
  - name: crossplane-aws-secretsmanager
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-secretsmanager.enabled
  - name: external-secrets
    version: "0.9.13-0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: external-secrets.enabled
