{{- $kind := "Provisioner" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if hasKey $item "enabled" | ternary ($item.enabled) (ne $kindObj.enabled false) }}
---
apiVersion: karpenter.sh/v1alpha5
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
spec:
    {{- include "common-gitops.tplvalues.render" (dict
      "value" (omit . "provider" "providerRef")
      "context" $root) | nindent 2 }}
    {{- with .provider }}
  provider:
      {{- include "common-gitops.tplvalues.render" (dict
        "value" (omit . "tags")
        "context" $root) | nindent 4 }}
    tags:
      {{- include "common-gitops.tags.dict" (dict "root" $root "name" $name "kind" $kind "nameOverride" .name) | nindent 6 }}
    {{- else }}
      {{- with .providerRef }}
  providerRef:
        {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
