# {{- $root := . }}{{- $resource := ($root.Values.GroupPolicyAttachment) }}
# {{- if $resource.enabled }}
# {{- range $resource.items }}
# ---
# apiVersion: iam.aws.crossplane.io/v1beta1
# kind: GroupPolicyAttachment
# metadata:
#   {{- $fullName := (print (include "common-gitops.names.name" $root) "-" .name "-grouppolicyattachment") }}
#   name: {{ $fullName }}
#   {{- include "common-gitops.aws.labels.full" (dict "root" $root "resource" $resource "item" .) | trim | nindent 2 }}
# spec:
#   {{- with .deletionPolicy }}
#   deletionPolicy: {{ . }}
#   {{- end }}
#   forProvider:
#     {{- if (.forProvider).groupNameRef }}
#     groupNameRef:
#       {{- include "common-gitops.tplvalues.render" (dict "value" .forProvider.groupNameRef "context" $root) | nindent 6 }}
#     {{- else if (.forProvider).groupNameSelector }}
#     groupNameSelector:
#       {{- include "common-gitops.tplvalues.render" (dict "value" .forProvider.groupNameSelector "context" $root) | nindent 6 }}
#     {{- else }}
#     groupName: "{{ required "groupName is required" (.forProvider).groupName }}"
#     {{- end }}
#     {{- if (.forProvider).policyArnRef }}
#     policyArnRef:
#       {{- include "common-gitops.tplvalues.render" (dict "value" .forProvider.policyArnRef "context" $root) | nindent 6 }}
#     {{- else if (.forProvider).policyArnSelector }}
#     policyArnSelector:
#       {{- include "common-gitops.tplvalues.render" (dict "value" .forProvider.policyArnSelector "context" $root) | nindent 6 }}
#     {{- else }}
#     policyArn: "{{ required "policyArn is required" (.forProvider).policyArn }}"
#     {{- end }}
#   {{- include "common-gitops.aws.publishConnectionDetailsTo" (dict "root" $root "resource" $resource "name" $fullName) | nindent 2 }}
#   {{- include "common-gitops.aws.providerConfigRef" $root | nindent 2 }}
# {{- end }}
# {{- end }}
