# {{- $root := . }}{{- $resource := ($root.Values.UserPolicyAttachment) }}
# {{- if $resource.enabled }}
# {{- range $resource.items }}
# ---
# apiVersion: iam.aws.crossplane.io/v1beta1
# kind: UserPolicyAttachment
# metadata:
#   {{- $fullName := (print (include "common-gitops.names.name" $root) "-" .name "-userpolicyattachment") }}
#   name: {{ $fullName }}
#   {{- include "common-gitops.aws.labels.full" (dict "root" $root "resource" $resource "item" .) | trim | nindent 2 }}
# spec:
#   {{- with .deletionPolicy }}
#   deletionPolicy: {{ . }}
#   {{- end }}
#   forProvider:
#     {{- if (.forProvider).policyArnRef }}
#     policyArnRef:
#       {{- include "common-gitops.tplvalues.render" (dict "value" .forProvider.policyArnRef "context" $root) | nindent 6 }}
#     {{- else if (.forProvider).policyArnSelector }}
#     policyArnSelector:
#       {{- include "common-gitops.tplvalues.render" (dict "value" .forProvider.policyArnSelector "context" $root) | nindent 6 }}
#     {{- else }}
#     policyArn: "{{ required "policyArn is required" (.forProvider).policyArn }}"
#     {{- end }}
#     {{- if (.forProvider).userNameRef }}
#     userNameRef:
#       {{- include "common-gitops.tplvalues.render" (dict "value" .forProvider.userNameRef "context" $root) | nindent 6 }}
#     {{- else if (.forProvider).userNameSelector }}
#     userNameSelector:
#       {{- include "common-gitops.tplvalues.render" (dict "value" .forProvider.userNameSelector "context" $root) | nindent 6 }}
#     {{- else }}
#     userName: "{{ required "userName is required" (.forProvider).userName }}"
#     {{- end }}
#   {{- include "common-gitops.aws.publishConnectionDetailsTo" (dict "root" $root "resource" $resource "name" $fullName) | nindent 2 }}
#   {{- include "common-gitops.aws.providerConfigRef" $root | nindent 2 }}
# {{- end }}
# {{- end }}
