annotations:
  category: Infrastructure
apiVersion: v2
# App version follows crossplane AWS provider version.
appVersion: "0.41.0"
description: A Helm chart for IAC resources needed by VPC
name: aws-vpc
version: "0.41.0-1"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/infra/aws-vpc
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: crossplane-aws-ec2
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-ec2.enabled
