annotations:
  category: Application
apiVersion: v2
appVersion: "0.40.11"
description: A Helm chart for argo-workflows
name: argo-workflows
version: "0.40.11-0"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/argo-workflows
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: argo-workflows
    version: "0.40.11"
    repository: https://argoproj.github.io/argo-helm
    condition: argo-workflows.enabled
  - name: crossplane-aws-iam
    version: "0.41.1"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
