annotations:
  category: Application
apiVersion: v2
appVersion: "1.13.2"
description: A Helm chart for Crossplane
name: crossplane
version: "1.13.2-31"
home: https://helm-repo-public.luminarinfra.com/
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/crossplane
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: crossplane
    version: "1.13.2"
    repository: https://charts.crossplane.io/stable
    condition: crossplane.enabled
  - name: prometheus-service-discovery
    version: "40.1.0-5"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: prometheus-service-discovery.enabled
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: common-gitops
    version: "1.1.7"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
