annotations:
  category: Application
apiVersion: v2
appVersion: "1.13.3"
description: A Helm chart for cert-manager
name: cert-manager
version: "1.13.3-0"
home: https://helm-repo-public.luminarinfra.com/
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/cert-manager
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: cert-manager
    version: "1.13.3"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: crossplane-aws-iam
    version: "0.37.0-1"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: crossplane-aws-iam.enabled
  - name: common-gitops
    version: "1.1.5"
    repository: https://helm-repo-public.luminarinfra.com/
