annotations:
  category: Application
apiVersion: v2
appVersion: "1.14.2"
description: A Helm chart for cert-manager
name: cert-manager
version: "1.14.2-0"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/cert-manager
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: cert-manager
    version: "v1.18.2"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: external-dns
    version: "6.33.0"
    repository: https://charts.bitnami.com/bitnami
    condition: external-dns.enabled
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: common-gitops
    version: "1.1.9"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
