annotations:
  category: Application
apiVersion: v2
appVersion: "5.43.3"
description: A wrapper Helm chart for loki scalable
name: loki-scalable
version: "5.43.3-3"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/loki-scalable
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: loki
    version: "6.33.0"
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: promtail
    version: "6.15.5"
    repository: https://grafana.github.io/helm-charts
    condition: promtail.enabled
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: crossplane-aws-s3
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-s3.enabled
  - name: crossplane-aws-secretsmanager
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-secretsmanager.enabled
  - name: external-secrets
    version: "0.9.13-2"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: external-secrets.enabled
