annotations:
  category: Infrastructure
apiVersion: v2
# App version follows crossplane AWS provider version.
appVersion: "0.37.0"
description: A Helm chart for managing eks configuration specs after eks cluster is deployed
name: aws-eks-config
version: "1.0.0"
home: https://helm-repo-public.luminarinfra.com/
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/infra/aws-ekc-config
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: common-gitops
    version: "1.1.2"
    repository: https://helm-repo-public.luminarinfra.com/
  - name: crossplane-aws-secretsmanager
    version: "0.37.0-1"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: crossplane-aws-secretsmanager.enabled
  - name: external-secrets
    version: "0.7.1-13"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: external-secrets.enabled
