---
## AWS KMS resources configurations

Alias:
  items:
    test:
      forProvider:
        region: us-west-2
        targetKeyIdRef:
          name: iac-infra-eks-cluster-key

Key:
  items:
    test:
      forProvider:
        policy: |-
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "Enable IAM User Permissions",
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:iam::123456789012:user/root"
                },
                "Action": "kms:*",
                "Resource": "*"
              }
            ]
          }
        region: us-west-2
        tags:
          k1: v1
