{{- $kind := "LaunchTemplate" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if hasKey $item "enabled" | ternary ($item.enabled) (ne $kindObj.enabled false) }}
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
spec:
    {{- include "common-gitops.crossplane.awsDeletionPolicy" (dict "root" $root "name" $name "kind" $kind) | nindent 2 }}
  forProvider:
    {{- with .forProvider }}
      {{- with .launchTemplateData }}
    launchTemplateData:
        {{- with .blockDeviceMappings }}
      blockDeviceMappings:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .capacityReservationSpecification }}
      capacityReservationSpecification:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .cpuOptions }}
      cpuOptions:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .creditSpecification }}
      creditSpecification:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .disableAPITermination }}
      disableAPITermination: {{ . }}
        {{- end }}
        {{- with .ebsOptimized }}
      ebsOptimized: {{ . }}
        {{- end }}
        {{- with .elasticGPUSpecifications }}
      elasticGPUSpecifications:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .elasticInferenceAccelerators }}
      elasticInferenceAccelerators:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .enclaveOptions }}
      enclaveOptions:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .hibernationOptions }}
      hibernationOptions:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .iamInstanceProfile }}
      iamInstanceProfile:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .imageID }}
      imageID: {{ . }}
        {{- end }}
        {{- with .instanceInitiatedShutdownBehavior }}
      instanceInitiatedShutdownBehavior: {{ . }}
        {{- end }}
        {{- with .instanceMarketOptions }}
      instanceMarketOptions:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .instanceRequirements }}
      instanceRequirements:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .instanceType }}
      instanceType: {{ . | quote }}
        {{- end }}
        {{- with .kernelID }}
      kernelID: {{ . | quote }}
        {{- end }}
        {{- with .keyName }}
      keyName: {{ . | quote }}
        {{- end }}
        {{- with .licenseSpecifications }}
      licenseSpecifications:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .metadataOptions }}
      metadataOptions:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .monitoring }}
      monitoring:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .networkInterfaces }}
      networkInterfaces:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .placement }}
      placement:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .ramDiskID }}
      ramDiskID: {{ . | quote }}
        {{- end }}
        {{- with .securityGroupIDs }}
      securityGroupIDs:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .securityGroups }}
      securityGroups:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .tagSpecifications }}
      tagSpecifications:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
        {{- with .userData  }}
      userData: {{ . | quote }}
        {{- end }}
      {{- end }}
    launchTemplateName: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name) }}
      {{- with .tagSpecifications  }}
    tagSpecifications:
        {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
      {{- end }}
      {{- with .versionDescription }}
    versionDescription: {{ . | quote }}
      {{- end }}
    {{- end }}
    {{- include "common-gitops.crossplane.awsRegion" (dict "root" $root "name" $name "kind" $kind) | nindent 4 }}
    {{- include "common-gitops.tags.list" (dict "root" $root "name" $name "kind" $kind "nameOverride" .name) | nindent 4 }}
    {{- include "common-gitops.crossplane.publishConnectionDetailsTo" (dict "root" $root "name" $name "kind" $kind "nameOverride" .name) | nindent 2 }}
    {{- include "common-gitops.crossplane.writeConnectionSecretToRef" (dict "root" $root "name" $name "kind" $kind "nameOverride" .name) | nindent 2 }}
    {{- include "common-gitops.crossplane.providerConfigRef" (dict "root" $root "name" $name "kind" $kind) | nindent 2 }}
  {{- end -}}
{{- end -}}
