{{- $kind := "ClusterSecretStore" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if hasKey $item "enabled" | ternary ($item.enabled) (ne $kindObj.enabled false) }}
---
apiVersion: external-secrets.io/v1beta1
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
spec:
    {{- with .conditions }}
  conditions:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
    {{- end }}
    {{- with .controller }}
  controller: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
    {{- end }}
    {{- with .provider }}
  provider:
      {{- with .aws }}
    aws:
      region: {{ include "common-gitops.crossplane.awsRegion" (dict "root" $root "name" $name "kind" $kind) }}
        {{- with .role }}
      role: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
        {{- end }}
        {{- with .service }}
      service: {{ include "common-gitops.tplvalues.render" (dict "value" .service "context" $root) | quote }}
        {{- else }}
      service: "SecretsManager"
        {{- end }}
        {{- with .auth }}
      auth:
          {{- with .jwt }}
        jwt:
            {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 10 }}
          {{- end }}
          {{- with .secretRef }}
        secretRef:
          accessKeyIDSecretRef:
            name: {{ $item.name | default (include "common-gitops.names.itemFullname" (dict "root" $root "name" $name)) }}
            key: {{ .awsAccessKeyId }}
            {{- with .namespace }}
            namespace: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
            {{- end }}
          secretAccessKeySecretRef:
            name: {{ $item.name | default (include "common-gitops.names.itemFullname" (dict "root" $root "name" $name)) }}
            key: {{ .awsSecretAccessKey }}
            {{- with .namespace }}
            namespace: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .akeyless }}
    akeyless:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .alibaba }}
    alibaba:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .doppler }}
    doppler:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .onepassword }}
    onepassword:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .senhasegura }}
    senhasegura:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .yandexcertificatemanager }}
    yandexcertificatemanager:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .fake }}
    fake:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .gcpsm }}
    gcpsm:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .gitlab }}
    gitlab:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .ibm }}
    ibm:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .oracle }}
    oracle:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .vault }}
    vault:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .webhook }}
    webhook:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .yandexlockbox }}
    yandexlockbox:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .azurekv }}
    azurekv:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
      {{- with .kubernetes }}
    kubernetes:
      auth:
        serviceAccount:
          name: {{ $item.name | default (include "common-gitops.names.itemFullname" (dict "root" $root "name" $name)) }}
        {{- with .remoteNamespace }}
      remoteNamespace: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
        {{- end }}
        {{- with .server }}
      server:
          {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .refreshInterval }}
    refreshInterval: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end }}
      {{- with .retrySettings }}
    retrySettings:
        {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 6 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
