---
Account:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider: {}

APIKey:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        name: test

Authorizer:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        authorizerCredentialsSelector:
          matchLabels:
            testing.upbound.io/example-name: restapi
        authorizerUri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:609897127049:function:official-providers-noop-test-func/invocations
        name: demo
        region: us-west-1
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: restapi

BasePathMapping:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        apiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: demo
        domainNameSelector:
          matchLabels:
            testing.upbound.io/example-name: example
        stageNameSelector:
          matchLabels:
            testing.upbound.io/example-name: example

ClientCertificate:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        description: My client certificate

Deployment:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: stage

DocumentationPart:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        location:
          - type: API
        properties: '{"description":"Example"}'
        region: us-west-1
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: restapi

DocumentationVersion:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        description: Example description
        region: us-west-1
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: restapi
        version: example_version

DomainName:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        certificateBody: <content of 'example.crt'>
        certificateChain: <content of ca.crt>
        certificateName: example-api
        certificatePrivateKeySecretRef:
          key: attribute.example.key
          name: example-secret
          namespace: upbound-system
        domainName: example.com

GatewayResponse:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        responseParameters:
          gatewayresponse.header.Authorization: '''Basic'''
        responseTemplates:
          application/json: '{"message":$context.error.messageString}'
        responseType: UNAUTHORIZED
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: restapi
        statusCode: "401"

IntegrationResponse:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        httpMethodSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        resourceIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        responseTemplates:
          application/xml: |
            #set($inputRoot = $input.path('$'))
            <?xml version="1.0" encoding="UTF-8"?>
            <message>
                $inputRoot.body
            </message>
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        statusCodeSelector:
          matchLabels:
            testing.upbound.io/example-name: integration

Integration:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        httpMethodSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        region: us-west-1
        resourceIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        type: MOCK

MethodResponse:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        httpMethodSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        region: us-west-1
        resourceIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        statusCode: "200"

MethodSettings:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        methodPath: '*/*'
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: stage
        settings:
          - metricsEnabled: true
        stageNameSelector:
          matchLabels:
            testing.upbound.io/example-name: stage

Method:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        authorization: NONE
        httpMethod: GET
        region: us-west-1
        resourceIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration

Model:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        contentType: application/json
        description: a JSON schema
        name: user
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        schema: |
          {
            "type": "object"
          }

RequestValidator:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        name: example
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: stage
        validateRequestBody: true
        validateRequestParameters: true

Resource:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        parentIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration
        pathPart: mydemoresource
        region: us-west-1
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: integration

RestAPIPolicy:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "*"
                },
                "Action": "execute-api:Invoke",
                "Resource": "<rest-api-arn>",
                "Condition": {
                  "IpAddress": {
                    "aws:SourceIp": "123.123.123.123/32"
                  }
                }
              }
            ]
          }
        region: us-west-1
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test

RestAPI:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        body: |-
          ${jsonencode({
              openapi = "3.0.1"
              info = {
                title   = "example"
                version = "1.0"
              }
              paths = {
                "/path1" = {
                  get = {
                    x-amazon-apigateway-integration = {
                      httpMethod           = "GET"
                      payloadFormatVersion = "1.0"
                      type                 = "HTTP_PROXY"
                      uri                  = "https://ip-ranges.amazonaws.com/ip-ranges.json"
                    }
                  }
                }
              }
            })}
        name: test-demo

Stage:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        deploymentIdSelector:
          matchLabels:
            testing.upbound.io/example-name: stage
        region: us-west-1
        restApiIdSelector:
          matchLabels:
            testing.upbound.io/example-name: stage
        stageName: development

UsagePlanKey:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        keyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: stage
        keyType: API_KEY
        usagePlanIdSelector:
          matchLabels:
            testing.upbound.io/example-name: stage

UsagePlan:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        apiStages:
          - apiIdSelector:
              matchLabels:
                testing.upbound.io/example-name: stage
            stageSelector:
              matchLabels:
                testing.upbound.io/example-name: stage
          - apiIdSelector:
              matchLabels:
                testing.upbound.io/example-name: stage
            stageSelector:
              matchLabels:
                testing.upbound.io/example-name: stage
        description: my description
        name: my-usage-plan
        productCode: MYCODE
        quotaSettings:
          - limit: 20
            offset: 2
            period: WEEK
        region: us-west-1
        throttleSettings:
          - burstLimit: 5
            rateLimit: 10

VPCLink:
  enabled: true
  deletionPolicy: Delete
  items:
    _:
      forProvider:
        description: example description
        name: example-${Rand.RFC1123Subdomain}
        region: us-west-1
        targetArnSelector:
          matchLabels:
            testing.upbound.io/example-name: vpclink
