annotations:
  category: Application
apiVersion: v2
appVersion: "2.6.5"
description: A Helm chart for cost-analyzer (kubecost)
name: cost-analyzer
version: "2.6.5-0"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/cost-analyzer
maintainers:
  - name: Luminar SRE Team
    email: ipe@luminartech.com
dependencies:
  - name: cost-analyzer
    version: "2.6.5"
    repository: https://kubecost.github.io/cost-analyzer/
    condition: cost-analyzer.enabled
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: crossplane-aws-s3
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-s3.enabled
  - name: common-res
    version: "1.0.15"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
