apiVersion: v2
name: chatbot-ui
description: A Helm chart for Crossplane
type: application
appVersion: "main" # Chatbot-ui does not have gold version yet
# Ref: https://github.com/mckaywrigley/chatbot-ui/tree/main
version: "0.1.1"
kubeVersion: ">=1.16.0-0"
annotations:
  category: Application
keywords:
  - chatgpt
  - chatbot
  - chatbot-ui
  - openai
home: https://helm-repo-public.luminarinfra.com/
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/chatbot-ui
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: common-gitops
    version: "1.1.7"
    repository: "ghcr.io/luminartech/helm-charts-public"
  - name: common-res
    version: "1.0.15"
    repository: "ghcr.io/luminartech/helm-charts-public"
    condition: common-res.enabled
  - name: crossplane-aws-secretsmanager
    version: "0.41.0"
    repository: "ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-secretsmanager.enabled
  - name: external-secrets
    version: "0.7.1-16"
    repository: "ghcr.io/luminartech/helm-charts-public"
    condition: external-secrets.enabled
