apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-get-token-script
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  get-token.sh: |
{{ .Files.Get "scripts/get-token.sh" | indent 4 }}
