nominatimInitialize:
  enabled: true
  pbfUrl: https://download.geofabrik.de/north-america/us-west-latest.osm.pbf
  importStyle: extratags

nominatimReplications:
  enabled: true
  replicationUrl: https://download.geofabrik.de/north-america/us-west-updates/

postgresql:
  primary:
    persistence:
      size: 500Gi
    extendedConfiguration: |
      shared_buffers = 2GB
      maintenance_work_mem = 10GB
      autovacuum_work_mem = 2GB
      work_mem = 50MB
      effective_cache_size = 24GB
      synchronous_commit = off
      max_wal_size = 1GB
      checkpoint_timeout = 10min
      checkpoint_completion_target = 0.9
      fsync = off
      full_page_writes = off