---
## AWS S3 bucket resources configurations
##############
# Global
##############
# global:
#   chartNameOverride: "infra"
#   releaseNameOverride: "infra"
#   tags: {}

Bucket:
  items:
    _:
      forProvider:
        region: us-west-1
        objectLockEnabled: true
        tags:
          Name: SampleBucket

BucketAccelerateConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: example
        status: Enabled

BucketACL:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3-canned
        acl: private

BucketAnalyticsConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        name: EntireBucket
        storageClassAnalysis:
        - dataExport:
          - destination:
            - s3BucketDestination:
              - bucketArnSelector:
                  matchLabels:
                    testing.upbound.io/example-name: s3

BucketCorsConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        corsRule:
        - allowedHeaders:
          - '*'
          allowedMethods:
          - PUT
          - POST
          allowedOrigins:
          - https://s3-website-test.upbound.com
          exposeHeaders:
          - ETag
          maxAgeSeconds: 3000
        - allowedMethods:
          - GET
          allowedOrigins:
          - '*'

BucketIntelligentTieringConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        name: EntireBucket
        tiering:
        - accessTier: DEEP_ARCHIVE_ACCESS
          days: 180
        - accessTier: ARCHIVE_ACCESS
          days: 125

BucketInventory:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        destination:
        - bucket:
          - bucketArnSelector:
              matchLabels:
                testing.upbound.io/example-name: s3-2
            format: ORC
        includedObjectVersions: All
        name: EntireBucketDaily
        schedule:
        - frequency: Daily

BucketLifecycleConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        rule:
          - id: rule-1
            status: Enabled
            filter:
              - prefix: "tmp/"
            expiration:
              - days: 90

BucketLogging:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        targetBucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3-2
        targetPrefix: log/

BucketMetric:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        name: EntireBucket

BucketNotification:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        topic:
        - events:
          - "s3:ObjectCreated:*"
          filterSuffix: ".log"
          topicArnSelector:
            matchLabels:
              testing.upbound.io/example-name: s3

BucketObject:
  items:
    _:
      forProvider:
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        key: new_object_key
        region: us-west-1
        contentBase64: dGhpcyBpcyBhIHRleHQg

BucketObjectLockConfiguration:
  items:
    _:
      forProvider:
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        region: us-west-1
        rule:
        - defaultRetention:
          - days: 5
            mode: COMPLIANCE

BucketOwnershipControls:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        rule:
        - objectOwnership: BucketOwnerPreferred

BucketPolicy:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        policy:
          Statement:
            VisualEditor0:
              Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:GetObject"
                - "s3:ListBucket"
              Resource:
                - "arn:aws:s3:::<bucket name>"
                - "arn:aws:s3:::<bucket name>/*"

BucketPublicAccessBlock:
  items:
    _:
      forProvider:
        region: us-west-1
        blockPublicAcls: false
        blockPublicPolicy: false
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3

BucketReplicationConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        role: <role ARN>
        rule:
        - destination:
          - bucketSelector:
              matchLabels:
                testing.upbound.io/example-name: s3
            storageClass: STANDARD
          filter:
          - prefix: foo
          id: foobar
          deleteMarkerReplication:
          - status: Enabled
          status: Enabled

BucketRequestPaymentConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        payer: Requester

BucketServerSideEncryptionConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        rule:
        - applyServerSideEncryptionByDefault:
          - kmsMasterKeyIdSelector:
              matchLabels:
                testing.upbound.io/example-name: s3
            sseAlgorithm: aws:kms

BucketVersioning:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        versioningConfiguration:
        - status: Enabled

BucketWebsiteConfiguration:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        errorDocument:
        - key: error.html
        indexDocument:
        - suffix: index.html
        routingRule:
        - condition:
          - keyPrefixEquals: docs/
          redirect:
          - replaceKeyPrefixWith: documents/

Object:
  items:
    _:
      forProvider:
        region: us-west-1
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        key: object_key
        contentBase64: dGhpcyBpcyBhIHRleHQg
      providerConfigRef:
        name: default

ObjectCopy:
  items:
    _:
      forProvider:
        bucket: destination_bucket_name
        grant:
        - permissions:
          - READ
          type: Group
          uri: http://acs.amazonaws.com/groups/global/AllUsers
        key: file_name
        region: us-west-1
        source: source_bucket_name/file_name
