{{- $kind := "StorageClass" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if hasKey $item "enabled" | ternary ($item.enabled) (ne $kindObj.enabled false) }}
---
apiVersion: storage.k8s.io/v1
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- with .allowVolumeExpansion }}
allowVolumeExpansion: {{ . }}
    {{- end }}
    {{- with .provisioner }}
provisioner: {{ . }}
    {{- end }}
    {{- with .reclaimPolicy }}
reclaimPolicy: {{ . }}
    {{- end }}
    {{- with .parameters }}
parameters:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 2 }}
    {{- end }}
    {{- with .volumeBindingMode }}
volumeBindingMode: {{ . }}
    {{- end }}
    {{- with .mountOptions }}
mountOptions: {{ . }}
    {{- end }}
    {{- with .allowedTopologies }}
allowedTopologies:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
