
Endpoint:
  items:
    _:
      direction: INBOUND
      ipAddress:
      - subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: sample-subnet1
      - subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: sample-subnet2
      name: foo
      region: us-west-1
      securityGroupIdRefs:
      - name: sg1
      tags:
        Environment: Prod

Rule::
  items:
    _:
      domainName: mycompany.test
      region: us-west-1
      ruleType: SYSTEM


RuleAssociation:
  items:
    _:
      region: us-west-1
      resolverRuleIdSelector:
        matchLabels:
          testing.upbound.io/example-name: sys
      vpcIdSelector:
        matchLabels:
          testing.upbound.io/example-name: sample-vpc
