## @section AWS resources


## @param AccessPoint resource parameters
##
AccessPoint: {}

## @param BackupPolicy resource parameters
##
BackupPolicy: {}

## @param FileSystemPolicy resource parameters
##
FileSystemPolicy: {}

## @param FileSystem resource parameters
##
FileSystem: {}

## @param MountTarget resource parameters
##
MountTarget: {}

## @param ReplicationConfiguration resource parameters
##
ReplicationConfiguration: {}