---
## AWS EFS resources configurations

AccessPoint:
  items:
    example:
      forProvider:
        fileSystemIDRef:
          name: example
        region: us-west-2

BackupPolicy:
  items:
    example:
      forProvider:
        backupPolicy:
          - status: ENABLED
        fileSystemIdRef:
          name: example
        region: us-west-2

FileSystemPolicy:
  items:
    example:
      forProvider:
        bypassPolicyLockoutSafetyCheck: true
        fileSystemIdSelector:
          matchLabels:
            testing.upbound.io/example-name: efs
        policy: |
          {
              "Version": "2012-10-17",
              "Id": "ExamplePolicy01",
              "Statement": [
                  {
                      "Sid": "ExampleStatement01",
                      "Effect": "Allow",
                      "Principal": {
                          "AWS": "*"
                      },
                      "Resource": "<file system ARN>",
                      "Action": [
                          "elasticfilesystem:ClientMount",
                          "elasticfilesystem:ClientWrite"
                      ],
                      "Condition": {
                          "Bool": {
                              "aws:SecureTransport": "true"
                          }
                      }
                  }
              ]
          }
        region: us-west-2

FileSystem:
  items:
    example:
      forProvider:
        region: us-west-2

MountTarget:
  items:
    example:
      forProvider:
        region: us-west-2
        fileSystemIDRef:
          name: example
        subnetIDRef:
          name: sample-subnet1
        securityGroupsRefs:
          - name: sample-cluster-sg

ReplicationConfiguration:
  items:
    example:
      forProvider:
        destination:
          - region: us-west-1
        region: us-west-2
        sourceFileSystemIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example
