---

DelegationSet:
  items:
    test:
      forProvider:
        referenceName: DynDNS
        region: us-west-1

HealthCheck:
  items:
    test:
      forProvider:
        failureThreshold: 5
        fqdn: mycompany.test
        port: 80
        region: us-west-1
        requestInterval: 30
        resourcePath: /
        tags:
          Name: crossplane
        type: HTTP

HostedZoneDNSSEC:
  items:
    test:
      forProvider:
        hostedZoneIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example
        region: us-west-1

Record:
  items:
    test:
      forProvider:
        region: us-west-1
        name: www
        records:
        - "dev.upbound.io"
        ttl: 5
        type: CNAME
        zoneIdRef:
          name: example

ResolverConfig:
  items:
    test:
      forProvider:
        autodefinedReverseFlag: DISABLE
        region: us-west-1
        resourceIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example

TrafficPolicy:
  items:
    test:
      forProvider:
        comment: example comment
        document: |
          {
            "AWSPolicyFormatVersion": "2015-10-01",
            "RecordType": "A",
            "Endpoints": {
              "endpoint-start-NkPh": {
                "Type": "value",
                "Value": "10.0.0.2"
              }
            },
            "StartEndpoint": "endpoint-start-NkPh"
          }
        name: example
        region: us-west-1

TrafficPolicyInstance:
  items:
    test:
      forProvider:
        hostedZoneIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example
        name: mycompany.test
        region: us-west-1
        trafficPolicyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example
        trafficPolicyVersion: 1
        ttl: 360

VPCAssociationAuthorization:
  items:
    test:
      forProvider:
        region: us-west-1
        vpcIdSelector:
          matchLabels:
            testing.upbound.io/example-name: alternate
        zoneIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example

Zone:
  items:
    test:
      forProvider:
        name: mycompany.test
        region: us-west-1

ZoneAssociation:
  items:
    test:
      forProvider:
        region: us-west-1
        vpcIdSelector:
          matchLabels:
            testing.upbound.io/example-name: secondary
        zoneIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example
