annotations:
  category: Application
apiVersion: v2
appVersion: "2.6.4"
description: A Wrapper Helm chart for argo-cd
name: argo-cd
version: "5.25.0-1"
home: https://helm-repo-public.luminarinfra.com/
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/argo-cd
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: argo-cd
    version: "5.25.0"
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
  - name: common-gitops
    version: "1.1.2"
    repository: https://helm-repo-public.luminarinfra.com/
  - name: crossplane-aws-iam
    version: "0.37.0-1"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: crossplane-aws-iam.enabled
  - name: external-secrets
    version: "0.7.1-15"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: external-secrets.enabled
  - name: common-res
    version: "1.0.12"
    repository: https://helm-repo-public.luminarinfra.com/
    condition: common-res.enabled
