annotations:
  category: Application
apiVersion: v2
appVersion: "2.14.2"
description: A Wrapper Helm chart for argo-cd
name: argo-cd
version: "7.8.2"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/argo-cd
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: argo-cd
    version: "7.8.2"
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
  - name: common-gitops
    version: "1.1.10"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: external-secrets
    version: "0.9.13-2"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: external-secrets.enabled
  - name: common-res
    version: "1.0.18"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: common-res.enabled
  - name: crossplane-aws-secretsmanager
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-secretsmanager.enabled
