{{- $kind := "Secret" -}}
{{- $root := . -}}
{{- $eventObj := or $root.Values.Events (dict) -}}
{{- range $event, $eventItem := $eventObj.items -}}
  {{- $eventName := (kindIs "invalid" .name | ternary (include "common-gitops.tplvalues.render" (dict "value" $event "context" $root)) (include "common-gitops.tplvalues.render" (dict "value" .name "context" $root))) -}}
  {{- range $eventSource, $eventSourceItem := .eventSources -}}
    {{- $eventSourceName := (kindIs "invalid" .name | ternary (print "event-" $eventName "-" (include "common-gitops.tplvalues.render" (dict "value" $eventSource "context" $root))) (include "common-gitops.tplvalues.render" (dict "value" .name "context" $root))) }}
---
apiVersion: v1
kind: {{ $kind }}
metadata:
    {{- with (.webhookSecret).name }}
  name: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | quote }}
    {{- else }}
  name: {{ $eventSourceName | quote }}
    {{- end }}
data:
    {{- with (.webhookSecret).key }}
  {{ print (include "common-gitops.tplvalues.render" (dict "value" . "context" $root)) ":" }} {{ randAlphaNum 64 | b64enc | quote }}
    {{- else }}
  webhook_secret: {{ randAlphaNum 64 | b64enc | quote }}
    {{- end -}}
  {{- end -}}
{{- end }}
