{{- $kind := "CronJob" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if eq (include "common-gitops.utils.itemEnabled" (dict "root" $root "name" $name "kind" $kind)) "true" }}
---
apiVersion: batch/v1
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.names.namespace" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
spec:
    {{- with .schedule }}
  schedule: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | quote }}
    {{- end -}}
    {{- with .jobTemplate }}
  jobTemplate:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
    {{- end -}}
  {{- end -}}
{{- end }}
