{{- $kind := "RoleBinding" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if eq (include "common-gitops.utils.itemEnabled" (dict "root" $root "name" $name "kind" $kind)) "true" }}
    {{- $itemName := (kindIs "invalid" .name | ternary (include "common-gitops.names.itemFullname" (dict "root" $root "name" $name)) (include "common-gitops.tplvalues.render" (dict "value" .name "context" $root))) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kind }}
metadata:
  name: {{ $itemName | quote }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.names.namespace" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- with .roleRef }}
roleRef:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 2 }}
    {{- else }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $itemName | quote }}
    {{- end }}
    {{- with .subjects }}
subjects:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 2 }}
    {{- else }}
subjects:
  - kind: ServiceAccount
    name: {{ $itemName | quote }}
    {{- end -}}
  {{- end -}}
{{- end }}
