{{- $kind := "ServiceAccount" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if hasKey $item "enabled" | ternary ($item.enabled) (ne $kindObj.enabled false) }}
    {{- $itemName := (kindIs "invalid" .name | ternary (include "common-gitops.names.itemFullname" (dict "root" $root "name" $name)) (include "common-gitops.tplvalues.render" (dict "value" .name "context" $root))) }}
---
apiVersion: v1
kind: {{ $kind }}
metadata:
  name: {{ $itemName | quote }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- with ($root.Values.global).imagePullSecrets }}
imagePullSecrets:
      {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 2 }}
    {{- end -}}
  {{- end -}}
{{- end }}
