{{- $kind := "Service" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if hasKey $item "enabled" | ternary ($item.enabled) (ne $kindObj.enabled false) }}
---
apiVersion: v1
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.names.namespace" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- with .spec }}
spec:
      {{- with .type }}
  type: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .ipFamilyPolicy }}
  ipFamilyPolicy: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .ports }}
  ports:
        {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
      {{- end }}
  selector:
    app.kubernetes.io/component: {{ include "common-gitops.names.chart" $root }}
    helm.sh/chart: {{ include "common-gitops.names.chart" $root }}-{{ $root.Chart.Version }}
    app.kubernetes.io/part-of: {{ include "common-gitops.names.release" $root }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    app.kubernetes.io/instance: "{{ include "common-gitops.names.itemId" $name }}"
      {{- with .selector -}}
        {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end }}
