{{- $kind := "Service" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if eq (include "common-gitops.utils.itemEnabled" (dict "root" $root "name" $name "kind" $kind)) "true" }}
---
apiVersion: v1
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.names.namespace" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- with .spec }}
spec:
      {{- with .type }}
  type: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .clusterIP }}
  clusterIP: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .ipFamilies }}
  ipFamilies: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .ipFamilyPolicy }}
  ipFamilyPolicy: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .sessionAffinity }}
  sessionAffinity: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ include "common-gitops.tplvalues.render" (dict "value" . "context" $root) }}
      {{- end -}}
      {{- with .ports }}
  ports:
        {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
      {{- end }}
  selector:
      {{- with .selector -}}
        {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
      {{ else }}
    app.kubernetes.io/component: {{ include "common-gitops.names.chart" $root }}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end }}
