annotations:
  category: Application
apiVersion: v2
appVersion: "6.28.6"
description: A Helm chart for external-dns
name: external-dns
version: "6.28.6-1"
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/external-dns
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: external-dns
    version: "6.28.6"
    repository: https://charts.bitnami.com/bitnami
    condition: external-dns.enabled
  - name: crossplane-aws-iam
    version: "0.41.0"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: crossplane-aws-iam.enabled
  - name: common-gitops
    version: "1.1.7"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
