---
external-dns:
  enabled: true
  aws:
    assumeRoleArn: arn:aws:iam::627218074315:role/external-dns
    roleArn: arn:aws:iam::627218074315:role/external-dns
    region: us-west-2
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::627218074315:role/external-dns
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

crossplane-aws-iam:
  enabled: true
