name: '[QUALITY] pre-commit'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4.3.0
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
