apiVersion: v2
name: devspace
description: A Helm chart for Devspace
type: application
appVersion: "6.3.12"
version: "6.3.12-0"
kubeVersion: ">=1.23.0-0"
annotations:
  category: Application
keywords:
  - devspace
  - devpod
home: "https://github.com/luminartech/helm-charts-public"
sources:
  - https://github.com/luminartech/helm-charts-public/tree/main/charts/modules/apps/devspace
maintainers:
  - name: Luminar IPE Team
    email: ipe@luminartech.com
dependencies:
  - name: common-gitops
    version: "1.1.9"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
  - name: common-res
    version: "1.0.17"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: common-res.enabled
